name: Node.js CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        os:
          - ubuntu-18.04
          - macos-10.14
            -
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
        if: succeeded() || failed()
        env:
          CI: true
      - run: bash <(curl -s https://codecov.io/bash)
